### ISSUE TITLE
SIGABRT during Luxmark 3.1 execution

### ISSUE THREAD

**Issue by JacekDanecki** [KhronosGroup/SPIRV-LLVM-Translator#404]
The issue was filled as [issue 218](https://github.com/intel/compute-runtime/issues/218) and was debugged as issue in spirv-llvm-translator when this library is compiled with optimization enabled.
To reproduce this issue, download [PKGBUILD file](https://git.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/spirv-llvm-translator), apply bellow patch to remove workaround. Run **makepkg** command to build package and it using: **pacman -U spirv-llvm-translator-9.0.0.1-3-x86_64.pkg.tar.xz** 

Patch to remove workaround:
```
@@ -26,7 +26,7 @@
     cmake ../${_srcname}-${pkgver%.*}-${_build} \
         -DBUILD_SHARED_LIBS=ON \
         -DCMAKE_BUILD_TYPE=Release \
-        -DCMAKE_CXX_FLAGS_RELEASE='-O0' \
+        -DCMAKE_CXX_FLAGS_RELEASE='-O2' \
         -DCMAKE_INSTALL_PREFIX=/usr \
         -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
         -DLLVM_INCLUDE_TESTS=ON \
```
Luxmark 3.1 was downloaded from [github release](https://github.com/LuxCoreRender/LuxMark/releases/download/luxmark_v3.1/luxmark-linux64-v3.1.tar.bz2)

Backtrace from gdb
```
free(): invalid pointer

Thread 3 "luxmark.bin" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe52fe700 (LWP 32154)]
0x00007ffff71c4f25 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff71c4f25 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff71ae897 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff7208258 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007ffff720f77a in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007ffff721114c in _int_free () from /usr/lib/libc.so.6
#5  0x00000000015474af in std::locale::_Impl::~_Impl() ()
#6  0x000000000154768d in std::locale::~locale() ()
#7  0x00007ffff70d32d4 in std::basic_streambuf<char, std::char_traits<char> >::~basic_streambuf (this=0x7fffe52fb598, __in_chrg=<optimized out>) at /build/gcc/src/gcc-build/x86_64-pc-linux-g
nu/libstdc++-v3/include/streambuf:204
#8  std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::~basic_stringbuf (this=0x7fffe52fb598, __in_chrg=<optimized out>) at /build/gcc/src/gcc-build[153/153]
c-linux-gnu/libstdc++-v3/include/sstream:65
#9  std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream (this=0x7fffe52fb580, __in_chrg=<optimized out>, __vtt_parm=<optimized out>) at
 /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/sstream:784
#10 0x00007fffeae41851 in SPIRV::OCL20ToSPIRV::getVecLoadWidth (DemangledName="vload3", this=0x7fffe3970290) at /usr/include/c++/9.2.0/istream:182
#11 SPIRV::OCL20ToSPIRV::visitCallVecLoadStore (this=this@entry=0x7fffe3970290, CI=CI@entry=0x7fffb02eca78, MangledName=..., OrigDemangledName="vload3") at /root/test3/spirv/src/SPIRV-LLVM-T
ranslator-9.0.0-1/lib/SPIRV/OCL20ToSPIRV.cpp:1363
#12 0x00007fffeae45376 in SPIRV::OCL20ToSPIRV::visitCallInst (this=0x7fffe3970290, CI=...) at /root/test3/spirv/src/SPIRV-LLVM-Translator-9.0.0-1/lib/SPIRV/OCL20ToSPIRV.cpp:483
#13 0x00007fffeae42c5e in llvm::InstVisitor<SPIRV::OCL20ToSPIRV, void>::delegateCallInst (I=..., this=0x7fffe3970290) at /usr/include/llvm/IR/Function.h:193
#14 llvm::InstVisitor<SPIRV::OCL20ToSPIRV, void>::visitCall (I=..., this=0x7fffe3970290) at /usr/include/llvm/IR/Instruction.def:209
#15 llvm::InstVisitor<SPIRV::OCL20ToSPIRV, void>::visit (I=..., this=0x7fffe3970290) at /usr/include/llvm/IR/Instruction.def:209
#16 llvm::InstVisitor<SPIRV::OCL20ToSPIRV, void>::visit<llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, false> > (End=..., Start=..., thi
s=0x7fffe3970290) at /usr/include/llvm/IR/InstVisitor.h:91
#17 llvm::InstVisitor<SPIRV::OCL20ToSPIRV, void>::visit (BB=..., this=0x7fffe3970290) at /usr/include/llvm/IR/InstVisitor.h:106
#18 llvm::InstVisitor<SPIRV::OCL20ToSPIRV, void>::visit<llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::BasicBlock, false, false, void>, false, false> > (End=..., Start=..., this
=0x7fffe3970290) at /usr/include/llvm/IR/InstVisitor.h:91
#19 llvm::InstVisitor<SPIRV::OCL20ToSPIRV, void>::visit (F=..., this=0x7fffe3970290) at /usr/include/llvm/IR/InstVisitor.h:102
#20 llvm::InstVisitor<SPIRV::OCL20ToSPIRV, void>::visit<llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Function, false, false, void>, false, false> > (End=..., Start=..., this=0
x7fffe3970290) at /usr/include/llvm/IR/InstVisitor.h:91
#21 llvm::InstVisitor<SPIRV::OCL20ToSPIRV, void>::visit (M=..., this=0x7fffe3970290) at /usr/include/llvm/IR/InstVisitor.h:98
#22 SPIRV::OCL20ToSPIRV::runOnModule (this=0x7fffe3970290, Module=...) at /root/test3/spirv/src/SPIRV-LLVM-Translator-9.0.0-1/lib/SPIRV/OCL20ToSPIRV.cpp:356
#23 0x00007fffebde4786 in llvm::legacy::PassManagerImpl::run(llvm::Module&) () from /usr/lib/libLLVM-9.so
#24 0x00007fffeaeec7a3 in llvm::writeSpirv (M=M@entry=0x7fffe2251f40, Opts=..., OS=..., ErrMsg="") at /root/test3/spirv/src/SPIRV-LLVM-Translator-9.0.0-1/lib/SPIRV/SPIRVWriter.cpp:2087
#25 0x00007fffeaeecc79 in llvm::writeSpirv (M=0x7fffe2251f40, OS=..., ErrMsg="") at /root/test3/spirv/src/SPIRV-LLVM-Translator-9.0.0-1/lib/SPIRV/SPIRVWriter.cpp:2073
#26 0x00007ffff49f68b5 in Compile () from /usr/lib/libopencl-clang.so.9
#27 0x00007ffff4adaf7b in ?? () from /usr/lib/libigdfcl.so.1
#28 0x00007ffff4adcac3 in ?? () from /usr/lib/libigdfcl.so.1
#29 0x00007ffff4ae0956 in ?? () from /usr/lib/libigdfcl.so.1
#30 0x00007ffff64e2072 in ?? () from /usr/lib/intel-opencl/libigdrcl.so
#31 0x00007ffff654a2aa in ?? () from /usr/lib/intel-opencl/libigdrcl.so
#32 0x00007ffff649ef20 in ?? () from /usr/lib/intel-opencl/libigdrcl.so
#33 0x00007ffff74d8d9b in clBuildProgram () from /usr/lib/libOpenCL.so.1
#34 0x000000000085ebe3 in cl::Program::build(std::vector<cl::Device, std::allocator<cl::Device> > const&, char const*, void (*)(_cl_program*, void*), void*) const ()
#35 0x00000000008760be in luxrays::OpenCLBVHKernels::OpenCLBVHKernels(luxrays::OpenCLIntersectionDevice*, unsigned int, luxrays::BVHAccel const*) ()
#36 0x0000000000872961 in luxrays::BVHAccel::NewOpenCLKernels(luxrays::OpenCLIntersectionDevice*, unsigned int, unsigned int, bool) const ()
#37 0x000000000084db36 in luxrays::OpenCLIntersectionDevice::Start() ()
#38 0x000000000082f14e in luxrays::Context::Start() ()
#39 0x000000000067f8dd in slg::RenderEngine::Start() ()
#40 0x00000000005eec8b in LuxRenderSession::Start() ()
#41 0x00000000005d18ca in LuxMarkApp::EngineInitThreadImpl(LuxMarkApp*) ()
#42 0x0000000000899d0a in thread_proxy ()
#43 0x00007ffff76424cf in start_thread () from /usr/lib/libpthread.so.0
#44 0x00007ffff72882d3 in clone () from /usr/lib/libc.so.6
```

**Comment by svenvh** [comment]
@JacekDanecki, did you try to extract the LLVM IR?  For example, calling `M->dump()` in frame 25 in the above stack trace could be a starting point.  It will increase the chances of someone picking up this issue if we have the LLVM IR available and even better if we can reproduce the issue by passing the LLVM IR to standalone `llvm-spirv`.

**Comment by JacekDanecki** [comment]
```
(gdb) info frame
Stack level 25, frame at 0x7fffe52d3a60:
 rip = 0x7fffeaee6c79 in llvm::writeSpirv
    (/root/test3/spirv/src/SPIRV-LLVM-Translator-9.0.0-1/lib/SPIRV/SPIRVWriter.cpp:2073); saved rip = 0x7ffff49db8b5
 called by frame at 0x7fffe52d3f40, caller of frame at 0x7fffe52d39c0
 source language c++.
 Arglist at 0x7fffe52d39b8, args: M=0x7fffe2259930, OS=..., ErrMsg=""
 Locals at 0x7fffe52d39b8, Previous frame's sp is 0x7fffe52d3a60
 Saved registers:
  rbx at 0x7fffe52d3a28, rbp at 0x7fffe52d3a30, r12 at 0x7fffe52d3a38,
  r13 at 0x7fffe52d3a40, r14 at 0x7fffe52d3a48, r15 at 0x7fffe52d3a50,
  rip at 0x7fffe52d3a58
gdb) l * $rip
0x7fffeaee6c79 is in llvm::writeSpirv(llvm::Module*, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (/root/test3/spirv/src/SPIRV-LLVM-Transl
ator-9.0.0-1/lib/SPIRV/SPIRVWriter.cpp:2073).
2068    bool llvm::writeSpirv(Module *M, std::ostream &OS, std::string &ErrMsg) {
2069      SPIRV::TranslatorOpts DefaultOpts;
2070      // To preserve old behavior of the translator, let's enable all extensions
2071      // by default in this API
2072      DefaultOpts.enableAllExtensions();
2073      return llvm::writeSpirv(M, DefaultOpts, OS, ErrMsg);
2074    }
2075
2076    bool llvm::writeSpirv(Module *M, const SPIRV::TranslatorOpts &Opts,
2077                          std::ostream &OS, std::string &ErrMsg) {
(gdb) call M->dump()
Cannot evaluate function -- may be inlined
```
SPIRV-LLVM-Translator was compiled with -DCMAKE_CXX_FLAGS_RELEASE='-O2 -g'

**Comment by svenvh** [comment]
> (gdb) call M->dump()
> Cannot evaluate function -- may be inlined

In that case adding `M->dump();` at the start of the `llvm::writeSpirv` method and recompiling the translator should allow extracting the LLVM IR.

**Comment by JacekDanecki** [comment]
I need to recompile llvm, as this symbol is not provided by libLLVM-9.so 
```
 /usr/lib/../lib/libLLVMSPIRVLib.so.9: error: symbol lookup error: undefined symbol: _ZNK4llvm6Module4dumpEv (fatal)

c++filt _ZNK4llvm6Module4dumpEv
llvm::Module::dump() const
```

**Comment by JacekDanecki** [comment]
I've recompiled llvm with -DLLVM_ENABLE_DUMP=ON, then clang, all IGC components and Neo. Luxmark crashed as already mentioned. Log from gdb with output from M->dump() attached in typescript.log file.

[typescript.log](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/files/4249753/typescript.log)

**Comment by AlexeySotkin** [comment]
I can't reproduce the problem in my environment.

**Comment by svenvh** [comment]
Thanks for providing the dump, @JacekDanecki. I haven't been able to reproduce either unfortunately.

**Comment by JacekDanecki** [comment]
Have you tried to reproduce this issue using Luxmark on Arch, or on another linux distribution, or did you use LLVM IR I've provided in log?

**Comment by AlexeySotkin** [comment]
I tried to reproduce on Ubuntu 16.04 using release built of llvm-spirv made on the same machine. I used your LLVM IR as input.

**Comment by JacekDanecki** [comment]
I've tried to reproduce abort on Arch using llvm-spirv tool and LLVM IR from log, but the translation passed without issue.
I've also dumped opencl kernel from Luxmark and compiled it with offline compiler ocloc, and compilation finished correctly.

**Comment by JacekDanecki** [comment]
If I replace [2 lines](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/llvm_release_90/lib/SPIRV/OCL20ToSPIRV.cpp#L308) to get vector width with some code without using std::stringstream, Luxmark works correctly.

**Comment by JacekDanecki** [comment]
I suspected problems with Luxmark itself, as dumped LLVM IR could be translated using llvm-spirv and opencl kernel compiled with ocloc. Thanks for information about LLVM IR translation.

I've executed luxmark using valgrind, and this time there was not abort, and Luxmark finished correctly, but valgrind found:
```
ERROR SUMMARY: 47 errors from 16 contexts (suppressed: 0 from 0)
```
Found errors were like:
- Mismatched free() / delete / delete []
- Invalid free() / delete / delete[] / realloc()
- Invalid read of size 8
- Invalid read of size 8
and pointed at luxmark binary.
There were few errors including llvm-spirv-translator like below
```
==6895== 1 errors in context 7 of 16:
==6895== Invalid free() / delete / delete[] / realloc()
==6895==    at 0x483B58B: operator delete[](void*) (vg_replace_malloc.c:651)
==6895==    by 0x154768C: std::locale::~locale() (in /root/src/luxmark-v3.1/luxmark.bin)
==6895==    by 0x57C0FA3: ~basic_streambuf (streambuf:205)
==6895==    by 0x57C0FA3: ~basic_stringbuf (sstream:65)
==6895==    by 0x57C0FA3: std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream() (sstream:784)
==6895==    by 0xF0F7840: getVecLoadWidth (OCL20ToSPIRV.cpp:314)
==6895==    by 0xF0F7840: SPIRV::OCL20ToSPIRV::visitCallVecLoadStore(llvm::CallInst*, llvm::StringRef, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (OCL20ToSPIRV.cpp:1370)
==6895==    by 0xF0FB375: SPIRV::OCL20ToSPIRV::visitCallInst(llvm::CallInst&) (OCL20ToSPIRV.cpp:490)
==6895==    by 0xF0F8C4D: delegateCallInst (InstVisitor.h:318)
==6895==    by 0xF0F8C4D: visitCall (Instruction.def:209)
==6895==    by 0xF0F8C4D: visit (Instruction.def:209)
==6895==    by 0xF0F8C4D: visit<llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, false> > (InstVisitor.h:91)
==6895==    by 0xF0F8C4D: visit (InstVisitor.h:106)
==6895==    by 0xF0F8C4D: visit<llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::BasicBlock, false, false, void>, false, false> > (InstVisitor.h:91)
==6895==    by 0xF0F8C4D: visit (InstVisitor.h:102)
==6895==    by 0xF0F8C4D: visit<llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Function, false, false, void>, false, false> > (InstVisitor.h:91)
==6895==    by 0xF0F8C4D: visit (InstVisitor.h:98)
==6895==    by 0xF0F8C4D: SPIRV::OCL20ToSPIRV::runOnModule(llvm::Module&) (OCL20ToSPIRV.cpp:363)
==6895==    by 0xA17FE65: llvm::legacy::PassManagerImpl::run(llvm::Module&) (in /usr/lib/libLLVM-9.so)
==6895==    by 0xF1A2702: llvm::writeSpirv(llvm::Module*, SPIRV::TranslatorOpts const&, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (SPIRVWriter.cpp:2087)
==6895==    by 0xF1A2BD8: llvm::writeSpirv(llvm::Module*, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (SPIRVWriter.cpp:2073)
==6895==    by 0xE4728B4: Compile (in /usr/lib/libopencl-clang.so.9)
==6895==    by 0x93F553D: TC::CClangTranslationBlock::TranslateClang(TC::TranslateClangArgs const*, TC::STB_TranslateOutputArgs*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char const*) (clang_tb.cpp:1508)
==6895==    by 0x93F7269: TC::CClangTranslationBlock::Translate(TC::STB_TranslateInputArgs const*, TC::STB_TranslateOutputArgs*) (clang_tb.cpp:1757)
==6895==  Address 0x230f3e0 is 0 bytes inside data symbol "_ZN12_GLOBAL__N_18name_vecE"
```
but they could occur because of other errors, or because Luxmark binary overwrite some functions from libstdc++.

Closing issue, as it looks like problem with luxmark 3.1 itself.
